version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:latest
    steps:
      - run:
          command: |
            touch ~/.ssh/known_hosts
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - checkout
      - run:
          command: |
            gem update --system
            gem install rubocop
            rubocop
workflows:
  version: 2
  build:
    jobs:
      - build
