version: 2
jobs:
  test:
    docker:
      - image: circleci/ruby:latest
    steps:
      - checkout
      - run: gem update --system
      - run: gem install rubocop --no-ri --no-rdoc
      - run: rubocop
workflows:
  version: 2
  test:
    jobs:
      - test
  