---
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: gem update --system
      - run: gem install rubocop
  test:
    docker:
      - image: circleci/ruby:latest
    steps:
      - checkout
      - run: rubocop
workflows:
  version: 2
test:
  jobs:
    - test
