---
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: gem install rubocop
      - run: rubocop
  test:
    docker:
      - image: circleci/ruby:latest
    steps:
      - checkout
      - run: rubocop
workflows:
  version: 2
build_and_test:
  jobs:
    - build
    - test
