version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:latest
    steps:
      - checkout
      - run:
          name: Gem setup
          command: |
            gem update --system
            gem install rubocop
          name: Rubocop run
          command: rubocop --config ./.rubocop/.rubocop.yml
workflows:
  version: 2
  build:
    jobs:
      - build
