version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:latest
    steps:
      - checkout
      - run:
          command: |
            gem update --system
            gem install rubocop
            rubocop
      - test:
          command: rubocop
          post:
            - bash <(curl -s https://codecov.io/bash)
workflows:
  version: 2
  build:
    jobs:
      - build
